# https://nicolas-van.github.io/easy-markdown-to-github-pages/
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - awesome-clothed-human.md
  - content/physical-world.md
  - content/3d-representation.md
  - content/over-domain-gap.md